name: C# Basics / test

on:
  push:
    branches: [ master ]

    paths:
      - '1-csharp-basics/**'
      
jobs:
  test:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./1-csharp-basics/CSharpBasics/CSharpBasics.sln
    - name: Build Debug
      run: dotnet build ./1-csharp-basics/CSharpBasics/CSharpBasics.sln --configuration Debug --no-restore
    - name: Build Release
      run: dotnet build ./1-csharp-basics/CSharpBasics/CSharpBasics.sln --configuration Release --no-restore
    - name: Tests
      run: dotnet test ./1-csharp-basics/CSharpBasics/CSharpBasics.sln --no-restore --no-build -v:n
